apiVersion: v1
kind: Secret
metadata:
  name: {{ include "web.fullname" . }}-db-auth
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    # Helm hook to create Secret before migration job
    "helm.sh/hook": pre-upgrade,pre-install
    "helm.sh/hook-weight": "-10"
type: Opaque
data:
  DATABASE_PASSWORD: {{ .Values.global.dbPassword | toString | b64enc }}
  EMAIL_HOST_PASSWORD: {{ .Values.global.emailHostPassword | toString | b64enc }}
{{/*  {{- with  .Values.imageSecrets }}*/}}
{{/*  AWS_ACCESS_KEY_ID: {{ .awsAccessKeyId }}*/}}
{{/*  AWS_SECRET_ACCESS_KEY: {{ .awsSecretAccessKey }}*/}}
{{/*  {{- end }}*/}}
