{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "web.serviceAccountName" . }}
  labels:
    {{- include "web.labels" . | nindent 4 }}
  annotations:
    # Helm hook to create ServiceAccount before migration job
    # No delete-policy: keep ServiceAccount for running pods
    "helm.sh/hook": pre-upgrade,pre-install
    "helm.sh/hook-weight": "-10"
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
